### ISSUE TITLE
polygon import does not work for geojson

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1179]
after choosing geojson-file and clicking upload, file is gone but not uploaded. shapefile works.

**Comment by kleingeist** [comment]
@MagdaN could you please append the geojson file u used? with the example files i had at hand everything worked fine.

the problem seems to be in the array buffer to string conversion. here are some info links how the conversion may be done:
[1] https://developers.google.com/web/updates/2012/06/How-to-convert-ArrayBuffer-to-and-from-String
[2] https://stackoverflow.com/questions/13031433/can-i-convert-arraybuffer-to-string

i have been using a solution from the second link, but as we get a max stack error it may be safer to use a for loop in our code

**Comment by MagdaN** [comment]
I used an export file from cartodb, you can download it [here](https://magdano.carto.com/tables/bezirksregionen/public/map) as Github does not allow to attach geojsons.

**Comment by kleingeist** [comment]
fixed with #1186
