### ISSUE TITLE
Ignore newsletter flag for platform newsletter

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-meinberlin#1369]

**Comment by phillimorland** [comment]
@MagdaN so our whole platform newsletter is currently ignoring the flag?

**Comment by CarolingerSeilchenspringer** [comment]
@MagdaN is this a relevant bug? can you explain it to me? :-)

**Comment by fuzzylogic2000** [comment]
We want to ignore the flag, but the it shouldn't be called newsletter. @CarolingerSeilchenspringer  will confirm

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer What is the behaviour we want to have? Should the "newsletter" go out to everyone (and ignore the flag) or should it only be sent to users that agreed to get newsletters?

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 still haven't talked to client, will do that tomorrow.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 in fact we need both the possibility to write to all registered user (e.g. if changing  datenschutzerklärung) AND to only write to those who allowed it (e.g. for asking to participate in an evaluation as we currently plan to do again). So I would suggest we make the newsletter NOT ignoring the flag (for the planned evaluation) for now. And then I will write a story to create something that ignores the flag to be able to write to everybody without exceptions. I won't close the story because I don't know how it is now and if you need to change something or if we already have what we want.
