### ISSUE TITLE
hitting enter submits idea unwillingly

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1495]
I had a user who did not want to submit her idea and said she did not hit "speichern" but still the idea was published (idea mapping). Sandy and I tested and believe that she hit enter while being either in the field for the title or the field "bezeichnung des markierten ortes" because then the idea gets submitted without further notification/question. Does this have to do with being barrier free? If yes it is still confusing, maybe we find a different solution?

**Comment by ihucos** [comment]
It is the default behavior for form tags.
Here is a blog post stating why this should not be suppressed: https://www.tjvantoll.com/2013/01/01/enter-should-submit-forms-stop-messing-with-that/

**Comment by fuzzylogic2000** [comment]
Yes! I always use enter to submit forms. I think people would be really annoyed if we supressed it, because they use it willingly. (Not even talking about the a11y issues it would introduce and are already brought up by @ihucos )
Also if you submit an idea, you are forwarded to the detail view of the idea you submitted. If you did it involuntarily, you can delete the idea again right away.
@CarolingerSeilchenspringer I will close this issue. If you still think we should change this default behaviour, reopen.
