### ISSUE TITLE
page with only name of author/moderator

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1885]
the Ergonomiegutachten pointed out this page (with anonymized name of moderator)

<img width="519" alt="bildschirmfoto 2019-01-31 um 14 28 09" src="https://user-images.githubusercontent.com/35491681/52057186-9cd9fd80-2564-11e9-97c1-3dbd144cc309.png">

they write: "Nach dem Aufruf dieser Maske gab es neben dem Namen des Moderators keine weiteren Informationen. Es ist nicht ersichtlich, wo man innerhalb der Anwendung steht, da z.B. ein Breadcrumb („Brotkrumennavigation“) fehlt."

I have no idea where they found this page. any clue?

**Comment by CarolingerSeilchenspringer** [comment]
yes, that's it @fuzzylogic2000, it's a profile page with only the username on it. Thanks for the hint. I can also see it as a user, not only as moderator. I guess this is an A4 feature? Do our other projects have it and do they show more? We should either not show the profile (is that even possible?) or make more out of it.

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer Well, it was a hard requirement to not have profile page on mB. But the problem here is not to turn off the profile page, but that in the comments, the username will have a link, because the comments are from a4. We can't change that and it would look superstrange, if the link would go to 404.

**Comment by CarolingerSeilchenspringer** [comment]
we will leave it like it is. Thanks @fuzzylogic2000
