### ISSUE TITLE
status bar AND project finished both shown on pop up

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1904]
![bildschirmfoto 2019-02-04 um 14 11 24](https://user-images.githubusercontent.com/35491681/52210297-ebe6a200-2886-11e9-8f4e-4360398140b8.png)

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer This project has three phases, two are active and one has ended. What is meant to happen here anyway? Do we always show the active phase, and if we don't have one the future phase and only if we don't have both the past one? Our wording is not necessarily right for projects with multiple phases, but I say, we do it anyway, because this currently shouldn't happen on productive (or very very seldomly),

**Comment by CarolingerSeilchenspringer** [comment]
"Do we always show the active phase, and if we don't have one the future phase and only if we don't have both the past one?" sound good to me for now, @fuzzylogic2000. We will include the pop up once we make a concept for multiple module.

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer This is a bit worse than it looked in the beginning. The stuff we have in A4 always assumes that only one phase is active at the same time. In the project you found here, three phases were active at the same time. Now, the one that started last has already ended. This messes up all assumptions we have in A4 and also (as you can see in the detail view of that project) makes problems on other ends on the page. We can't solve that here with the participation overview. So, for the participation overview, I propose we fix that two status bars are shown. This might still result in the filters behaving a bit strangely if the phases run at the same time.
But on productive there shoudn't be any projects where someone (can currently be only you or Daniel) used the "add module" as experimentally as done in this case. And later we have to tackle this whole logic with the "add module" anyway.
