### ISSUE TITLE
don't show/change button "weitere Filter" if filter is extended

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1925]
If I open the extended filter, the button "weitere Filter" is still there but makes no sense. This is especially wired on smartphone. Can we change the wording to e.g. "weniger Filter"?

<img width="429" alt="bildschirmfoto 2019-02-05 um 12 27 59" src="https://user-images.githubusercontent.com/35491681/52270621-cb2f5280-2941-11e9-9db7-c12edcb2d2b9.png">

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer Well, on smartphone we will have an overlay, so that you can't see it anyway. 
Should we change the wording on Desktop when the secondary filters are open? Maybe "Filter schliessen"? I am not sure this is a good idea, though? @szukowski what do you think?
And for tablet: what should happen there? The same icon is still fine no matter if the secondary filters are open or closed?

**Comment by CarolingerSeilchenspringer** [comment]
It was worse on mobile, this changed, so I will close.
