### ISSUE TITLE
links within texts are hard to see

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1926]
blue links within black texts are difficult to see. Can we have a different color? I found it on the LP but this is also true for e.g. "Information" within projects.

<img width="250" alt="bildschirmfoto 2019-02-05 um 12 35 28" src="https://user-images.githubusercontent.com/35491681/52271054-e64e9200-2942-11e9-8403-98416ad5aac3.png">

**Comment by phillimorland** [comment]
We changed default link colour for whole site after new design, @szukowski shall we change it back? this would also affect the storefront and tiles as link colour should be the same throughout the whole site

**Comment by szukowski** [comment]
@phillimorland @CarolingerSeilchenspringer  instead of switching back to pink please do the following:
Links within texts (text links) are displayed underline
Other links like headlines, buttons and tabs do not get underlined

**Comment by phillimorland** [comment]
@szukowski @CarolingerSeilchenspringer ok this could be a little tricky as link behavior is set in base and is universal, we don't have different class names for headline. paragraph, input, div links, I could add a nested style for all p, label and maybe input links but I don't think that will cover all of them and could cause style leaking. 
Is there a universal option we can try? this is also better for consistency but also much quicker otherwise it's going through whole site and adding class names to every link which is not ideal.

**Comment by CarolingerSeilchenspringer** [comment]
as discussed with @phillimorland and @szukowski : ideally we have an underlined version for links within text that come from wagtail and from projects (only CK-Editor)
