### ISSUE TITLE
make district obligatory for projects

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1929]
for projects:
there is not red ! net to Orte, although the district is obligatory (the localisation isn't)
Per default we have --- and not gesamtstädtisch (which is missing). The project is not published but I don't get a warning. 

Can we make a little red ! next to "Ort" even if per default we have "gesamtstädtisch"? Otherwise I might not see that my project is listet as gesamtstädtisch per default because I think that "Ort" is not relevant for me.

And add a * to Bezirk

<img width="316" alt="bildschirmfoto 2019-02-05 um 13 54 19" src="https://user-images.githubusercontent.com/35491681/52274792-08014680-294e-11e9-9804-3d4da8a73238.png">

<img width="316" alt="bildschirmfoto 2019-02-05 um 13 54 29" src="https://user-images.githubusercontent.com/35491681/52274793-08014680-294e-11e9-9efc-f94eade412a3.png">

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer I thought you already talked about it in the dashborad meeting? We can't. 
Gesamtstadtisch is our none-value, that means it replaces (or still needs to replace) the dashes in the dropdown. But we can't know if someone already chose gesamtstädtisch by purpose or if it's there because it's the default. And because of that we can't have the red exclamation mark.
If we change that, it will give us trouble in the filters and everywhere where the topics are used or displayed.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 as discussed, change "Ort" in navigation to "Bezirk und Ort" and see if it is too long. This way initiatory may see that this tab is relevant for them.
