### ISSUE TITLE
storefront item and comment count - only count user generated content

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#2163]
The items include
- ideas
- mapideas
- proposals from kiezkasse and budgeting
- topics
- maptopics
- polls
- chapters

Instead we could only seperately count:
- ideas
- mapideas
- proposals from kiezkasse and budgeting

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer This is about the counting on the landing page, the number for "von Bürger*innen eingereichte Ideen und Kommentare". We do currently count all items, that means, that we count all ideas and proposals, but also topics, maptopics, polls and chapters, which are all added by initiators, not the normal users. That we count too much is also the downside of it. The upside is, that we don't need to remember to add new items in case we add another module with new ones.
Currently we count 9579 Items (and 24547 Comments). If we would only count the real usergenerated things, we would have 8240 Ideas (and so on). 
What's the decision here? Change it or close the issue?

**Comment by fuzzylogic2000** [comment]
Remember live questions if changed. 
https://github.com/liqd/a4-meinberlin/blob/da8fbb3b7a1ab414290fcf2d6d91cf94c973f000/meinberlin/apps/projects/templatetags/meinberlin_project_tags.py

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 the live questions are also in? I tend to say that we should not count it because on prod we have over 35000 Beiträge and the few chapters and poll questions don't make a big difference. BUT: on modul level (modul tile in multimodule) it may be questioned because here it is more obvious. As I remember you said that it is difficult to do as long as modules don't know what kind of modules they are. Is that correct? Maybe we should make two stories out of it: 1) teach modules to know themselves and 2) straighten out counting everywhere?

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 ok, got that. So I will close this issue but have one more question: we do not count replys on landing page or in general, right? In one project we moderated the client was confused because the module tile had lower number than the one in my evaluation because the module tile did not count replies. Is that something we could generally change?

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer On the landing page we do count replies. I thought we also include them on the module tiles, but seems like I am wrong, then. Where else do we count comments? On top of the comments, right? Oh, no, the idea list. I think there we do only count the main comments and not the replys. These three are different things and are counted in different places. The one on the ideas in a4, so we can't just change it as we like.
