### ISSUE TITLE
Review phase and project description - what and where to display

### ISSUE THREAD

**Issue by phillimorland** [liqd/a4-meinberlin#2438]

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland Should I think of some helptext to make the difference of project/phase/module description more obvious?

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer was this to do with having the autofilled module description?

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland you started the issue and I understood that the difference between the project, module and phase description is unclear (user perspective). But maybe you meant something else? Currently the project description is the teasertext, that is quite clear. The modul description has a helptext but I guess it is confusing that something in "Grundeinstellungen" is only displayed if you have a timeline. Phase desription has no helptext at all and many initiators use the very basic and not so inviting texts that are autofilled. That's why I suggest not autofilled text plus a helptext in this case would improve UX.

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer I can't remember what exactly this was about but I think it came from people being confused about the difference between all the required descriptions and I wrote an issue as a reminder

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer should this still be open? should it be concepted? as I mentioned above, I think I wrote it as during testing it was confusing for users about what was displayed where but without a clear guide or concept I am not sure how to fix this?!

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland this is a general question, I will take it with me and bring it into concepting.
