### ISSUE TITLE
Cost for proposals should be emphasized

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-meinberlin#249]
When I read a proposal for a participatory budget is very central. It would be great, if we could emphasize the budget visually and give it a label „Estimated cost by user“ or similar. I would also use dividers for thousands of euros like so: 1.000.000 €

Could we show the cost in the list view, too? 

<img width="233" alt="bildschirmfoto 2017-04-24 um 15 46 49" src="https://cloud.githubusercontent.com/assets/15341015/25340216/550d5c0c-2905-11e7-8784-bc18c9c71e5d.png">

**Comment by damusp** [comment]
Following the design, the estimated cost should be shown in a label like this: 

![budget_label](https://cloud.githubusercontent.com/assets/22769111/25381131/e90a6834-29b2-11e7-9849-20bc833ccf2a.png)

Do you agree with this? Or should I think of something else?

**Comment by rittermo** [comment]
I think this is already much better! However, I would probably emphasize it even more. For participatory budgeting the estimated cost is as important as a map location for spatial brainstorming. Also, making more space for this information would give us an opportunity to add a small label and/or explanation that is an estimated cost by the author and that this is normally not based on official calculations.

**Comment by vellip** [comment]
https://docs.djangoproject.com/en/1.11/ref/contrib/humanize/ can help with the formatting of numbers. This seems desirable.

**Comment by damusp** [comment]
Here's a design that puts greater emphasis on the badges (they're bigger now).

![dhtrgsfdgfser](https://cloud.githubusercontent.com/assets/22769111/25709102/aa0f894c-30e8-11e7-9506-7f3db40d6562.png)

I believe that "estimated cost"-label is not needed because it's already quite obvious in the context of . Also, there are already plenty of informations buzzing around in this view, so it's better to keep it tidy. If we really want to integrate that extra piece of information we should probably rethink the use of badges.

**Comment by xi** [comment]
All suggestions have been implemented in #330.
