### ISSUE TITLE
Styling issues in header area at 800px width

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-meinberlin#259]
The header area shows some strange styling errors when the width is set to 800px (tested on Safari 10.0.3). 

1. The menu is always shown in an open state
2. The label for the project type has almost no vertical margin to the top navigation 

The seocond problem persists even for smaller widths. The first problem I can only produce at 800px viewport width.

![bildschirmfoto 2017-04-25 um 15 25 33](https://cloud.githubusercontent.com/assets/15341015/25387656/ea86ef66-29cb-11e7-8045-07ec79138bf4.png)

**Comment by xi** [comment]
Nice catch! I guess this is because we sometimes use `min-width` and sometimes `max-width` in media queries. So on the exact breakpoint, none of the media quries match. We should really stick to `min-width` (mobile first). This may not always be possible, but we should at least find a solution for this specific case.

Note that the exact width depends on browser settings because the breakpoint is defined as 50em. For me it was 750px.

**Comment by xi** [comment]
#264 fixes most issues, except for the user dropdown. @vellip do you have any idea how to fix that?

**Comment by vellip** [comment]
We can close that now, right?
