### ISSUE TITLE
testing 2394: navigation to main menu coming from other than participation project

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2681]
**URL:** https://meinberlin-dev.liqd.net/dashboard/organisations/caros-testorga/projects/
**user:** initiator/group member
**expected behaviour:** after editing/creating a b-plan/container/vorhaben/external project and I hit "back to main menu" I think I go back to the list I came from.
**behaviour:** instead I always go back to participation projects.
**important screensize:**
**device & browser:** 
**Comment/Question:** not crucial, better ux/ui though.

**Comment by fuzzylogic2000** [comment]
I thought, we decided that it will be like that. Should it change and the "main menu" is always something different?

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 hm, that was what I expected but I am not 100% sure that this would be the right UX. Maybe we should ask @MagdaN and @phillimorland and @rmader ?

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer @fuzzylogic2000 the link says main menu so it kind of makes sense but as a user it is disorientating because it still says 'back' and so you would expect to go back to the last place you were. 
If viable I think we should change it to 'back to list' and send it back to the list they came from. 
If that's too tricky, I think we change the wording to just say 'Main menu' removing the 'back' might help with expectation

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland @fuzzylogic2000 I think that is a great idea. If we go back to list user comes from, in german I would call it: zurück zur Übersicht (in English "list" may be better than "overview" though).

**Comment by fuzzylogic2000** [comment]
If we are going back to different lists anyway, we can also display different wording if you like.

**Comment by CarolingerSeilchenspringer** [comment]
I think "<- zurück zur Übersicht Bebauungspläne" is too long. Maybe "<- alle Bebauungspläne"? Does that work UX-wise?

**Comment by fuzzylogic2000** [comment]
fixed by #2710
