### ISSUE TITLE
When adding a new module the module is saved before I even filled in the data

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-meinberlin#2729]
**URL:** In dashboard after choosing a blueprint
**user:** initiator
**expected behaviour:** I see a form for creating the new module
**behaviour:** I see a form for updating a module (the module was already created when I chose the module)
**Comment/Question:** @CarolingerSeilchenspringer is this a problem?

**Comment by MagdaN** [comment]
We should change this as soon as there is time

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 @phillimorland lets discuss this again. This was part of the initial design but we should discuss this together with #2438 because the question is: What is the proper module description? As description in Grundeinstellungen is not always shown, the phase description is mostly more important.

**Comment by fuzzylogic2000** [comment]
I think this would be more about adding a modal to fill in these fields before the module is added, so that the user fills them in consciously

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 As discussed with @mcastro-lqd and @phillimorland this does not make a big difference in the actual process so I will close this issue. If you disagree please reopen.
