### ISSUE TITLE
make wording in external project/ bplan consistent in form/alerts/status guide

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2897]
**URL:** dashboard
**user:** initiator
**expected behaviour:** I have a clear wording that is the same in status guide as well as in all headlines, alerts and helptexts for external projects and bplans
**behaviour:** there is a mix of wording that is confusing
**important screensize:**
**device & browser:** 
**Comment/Question:**  so here is what @fuzzylogic2000 and I though of:
1) status-guide for external projects and bplans should be: Projekt anlegen, Projektdetails ausfüllen, Projekt veröffentlichen (so same wording as for projects, exception: containers remain containers in status guide; please note that right now it says "erstellen" instead of "anlegen", that should also be changed)
2) change form to start external project/bplan from "Verlinkung/Bebauungsplan anlegen" to "Projekt anlegen"
3) change alert "der Bebauungsplan/die Verlinkung wurde angelegt" to "Das Projekt wurde angelegt."
4) change header of forms "Bebauungsplan/ Externes Projekt bearbeiten" to "Einstellungen bearbeiten"

**Comment by fuzzylogic2000** [comment]
- [ ] status-guide for external projects and bplans should be: Projekt anlegen, Projektdetails ausfüllen, Projekt veröffentlichen (so same wording as for projects, exception: containers remain containers in status guide; 

- [ ] please note that right now it says "erstellen" instead of "anlegen", that should also be changed)

- [ ] change form to start external project/bplan from "Verlinkung/Bebauungsplan anlegen" to "Projekt anlegen"

- [ ] change alert "der Bebauungsplan/die Verlinkung wurde angelegt" to "Das Projekt wurde angelegt." 

- [ ] change header of forms "Bebauungsplan/ Externes Projekt bearbeiten" to "Einstellungen bearbeiten"
