### ISSUE TITLE
#3491 [mB] add video embed to interactive event 

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#3244]
**URL:** https://meinberlin-dev.liqd.net/projekte/design-project/
**device & browser:** *Safari Version 14.0 (15610.1.28.1.9, 15610)*
**Comment/Question:** 
*Just to confirm, the live stream field should appear just when the project is published? Cause, I can't select the live stream section before being published, otherwise all good*  

<img width="1361" alt="Screenshot 2020-11-10 at 16 03 41" src="https://user-images.githubusercontent.com/59610786/98691968-e462ff80-236e-11eb-904b-755ff83b79cc.png">
<img width="1389" alt="Screenshot 2020-11-10 at 16 04 07" src="https://user-images.githubusercontent.com/59610786/98691978-e7f68680-236e-11eb-9a18-53ade0537fa8.png">
<img width="1330" alt="Screenshot 2020-11-10 at 16 04 24" src="https://user-images.githubusercontent.com/59610786/98691980-e927b380-236e-11eb-88a8-ad2c644e58df.png">

**Comment by phillimorland** [comment]
@fuzzylogic2000 were you on this? it sounded like you knew what the problem was during standup? if not I can take a look

**Comment by fuzzylogic2000** [comment]
@phillimorland I've only seen it and knew, where I didn't really read, what I copied. It's here: https://github.com/liqd/a4-meinberlin/blob/842bcc2dee35488df471d952cfd1c401358a9078/meinberlin/apps/livequestions/dashboard.py#L15 The last bit should go, so that it is True, when it is in the right module, but the module doesn't need to be published.

**Comment by phillimorland** [comment]
oh danke darling, i'll get on that :)
