### ISSUE TITLE
#3492 [mb] change UX of entering questions - #3530 UX/UI testing 

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#3291]
**URL:** https://meinberlin-dev.liqd.net/projekte/module/interaktive-veranstaltung-11/
**important screensize:** *Both*
**device & browser:** *Safari, Version 14.0 (15610.1.28.1.9, 15610) + Safari for iOS*
**Comment/Question:**

**Desktop:**
[201201-d-change-UX-of-entering-questions.pdf](https://github.com/liqd/a4-meinberlin/files/5624001/201201-d-change-UX-of-entering-questions.pdf)

**Mobile:**
[201201-m-change-UX-of-entering-questions.pdf](https://github.com/liqd/a4-meinberlin/files/5624002/201201-m-change-UX-of-entering-questions.pdf)

Let me know if something is unclear! 
Thanks

**Comment by phillimorland** [comment]
@mcastro-lqd as theres no number on the comments i'm just going by the order that they appear, if you can number them in future that would be awesome! danke!
Desktop:
1. as discussed in other issue, i can sort out the width but as it is a select not a filter we can't use the same element type so it will look like the other selects we use on the site not the dropdowns.
2. links are broken in dev as pages don't exist
3. this is a great idea but it's an enhancement, if it proves quick will add it, otherwise will have to go into a polishing story.
4. blue filter -  to be fixed

Mobile
1. filter placement - to be fixed
2. again we can't use a dropdown as a select element in a form, we have to use a select element to send data to the database unless we write a bunch of custom code to make it work, I'll see what I can do for mobile but the browser is responsible for at least some of the styling of selects so it's a little limited
