### ISSUE TITLE
testing 3781: participatory budgeting 2 phases

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3396]
**URL:** https://meinberlin-dev.liqd.net/projekte/module/burgerinnenhaushalt-2-phase-2/
**user:** registered and unregistered user
**expected behaviour:** 1 phase: there is no indicator that I can already rate ideas
**behaviour:** ratings seem clickable but are not 
**important screensize:**
**device & browser:** 
**Comment/Question:** it is possible to make the ratings grey in the first phase? @mcastro-lqd what do you think is best ux wise?

<img width="206" alt="Bildschirmfoto 2021-02-15 um 17 27 13" src="https://user-images.githubusercontent.com/35491681/107971934-63418700-6fb3-11eb-9cac-a90f34bc0716.png">
<img width="405" alt="Bildschirmfoto 2021-02-15 um 16 43 11" src="https://user-images.githubusercontent.com/35491681/107971929-62105a00-6fb3-11eb-85da-4d616eb39177.png">
<img width="630" alt="Bildschirmfoto 2021-02-15 um 16 49 06" src="https://user-images.githubusercontent.com/35491681/107971933-63418700-6fb3-11eb-9d09-ee9401d67867.png">

**Comment by fuzzylogic2000** [comment]
There's two different things here: The first and the last image are the lists, where the rating numbers are never clickable, but only show how many rates the idea got. I don't think, we should change that with the phase. So, I mean, the numbers on the list should always have the same colour. Maybe not necessarily green and red, because they do really look very clickable.
On the detail page, the middle image, I think you're right! It should be more easily recognizable that rating is not possible. Currently that is mainly done via the hover-behaviour. But again, this should be the same everywhere and for example if a phase is over also should look less inviting.

**Comment by CarolingerSeilchenspringer** [comment]
I will make a story out of it and include both: 1) in list should not look clickable and in idea) should not be active in 1st phase
