### ISSUE TITLE
test 4294: show "my answer" in open questions

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3738]
**URL:** https://meinberlin-dev.liqd.net/projekte/test-poll-merge-running-poll-with-user-content/
**user:** registered
**expected behaviour:** when clicking though the open text answers on result page I know which of them was mine
**behaviour:** no indication (no red colour, no check)
**important screensize:**
**device & browser:** 
**Comment/Question:** As I understood the red colour that was originally in the design was too difficult. @mcastro-lqd then had the idea below with the check in front of the answer (screenshot from zeplin). Is this also too difficult? @mcastro-lqd suggested we could also use the line with the numbers (bottom right corner) or always show "my answer" at first. What do you think is still doable, @phillimorland ?

Screenshot?
<img width="823" alt="Bildschirmfoto 2021-07-14 um 11 51 24" src="https://user-images.githubusercontent.com/35491681/125602259-01a86772-899c-4089-aa62-c6f457593ef0.png">

**Comment by khamui** [comment]
I think the reason for the checkmark icon is because better recognition for a11y. @phillimorland correct me if i am wrong.
Color won't be recognized for screenreaders i guess.

Answering because I was working on that part. So technically we managed to do anything of marking the users answer: checkmark, colors or/and `My answer` (this needs translations, to be considered) would be possible.

**Comment by CarolingerSeilchenspringer** [comment]
thanks @khamui I would leave the decision to @mcastro-lqd. If possible it would be nice to have it and for me all solutions are fine although I prefer the check because that is what we do for the multiple choice answers.

**Comment by phillimorland** [comment]
should be fixed in next merge
