### ISSUE TITLE
dashboard: Should not filled in required fields trigger an additional notification?

### ISSUE THREAD

**Issue by sabinammm** [liqd/a4-meinberlin#3990]
**URL:** https://meinberlin-dev.liqd.net/dashboard/projects/sabinas-bebauungsplan/bplan/
**user:** Project initiators who want to add a Bplan 
**expected behaviour:** If I forget to add a field, I am reminded of it in a way that helps me correct this.
**behaviour:** I am alerted to a missing required field with a small browser-dependent error message only in english. Fields that are only required for publication do not give me a special error message.
**important screensize:** any
**device & browser:** ubuntu chrome
**Comment/Question:** 
For a required title field, this is the same as issue #3989 
@CarolingerSeilchenspringer do you want these errors to be shown also with a dark red box at the top and the bottom? And do you think that the fields only required upon publication like e-mail address with an exclamation point should throw errors as well?

Screenshot?
**Current error for missing required field in Bplan:**
![image](https://user-images.githubusercontent.com/17978375/143581364-6d266d38-3788-4b47-a20e-dd9682f17ff4.png)

**Comment by fuzzylogic2000** [comment]
The first bit is analogous to #3989, as you also said and should be handled there.
So, this issue is about the fields missing for publication. They do not show errors when they are missing upon save, because they are not really required. They are only required for publication. We do the same in the "normal" project and module forms. It is a good question, though if we want an additional alert if someone fills in a form with fields required for publication and leaves some of that out. Currently we only have the exclamation mark next to the nav and next to the field. Do we also want another alert at the top like "not all fields reuiqred for publication are filled in"? @CarolingerSeilchenspringer

**Comment by CarolingerSeilchenspringer** [comment]
@sabinammm @fuzzylogic2000 I would leave it with the red exclamation mark. This gives flexibility to fill those fields in later. So I'd say the error message should only appear, when the form cannot be saved due to missing/wrong information.

**Comment by fuzzylogic2000** [comment]
Alright! Se, we will leave it at that!
