### ISSUE TITLE
testing 5024: default for archived filter not working in react proposal list

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#4101]
**URL:** https://meinberlin-dev.liqd.net/projekte/burgerhaushalt-spandau/?mode=list&ordering=-created&is_archived=true
**user:** any
**expected behaviour:** setting filter "archived" on "no" does not show archived ideas
**behaviour:** archived ideas are included in the list
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by fuzzylogic2000** [comment]
This is a bit of a mix of issues:
The link you added will never work, because the filters in React work differently as discussed in the story.

But this is still an issue: because the filters do not work initially. When the list is opened the first time, the archived proposals should be filtered out, like the filter already shows. That is nor working. When you select "Nein" in the archived filter again, though, the right list is shown. Will change the title!
