### ISSUE TITLE
style issues from removal of style lib

### ISSUE THREAD

**Issue by phillimorland** [liqd/a4-meinberlin#4515]
buttons: 

- [x] button light grey hover too dark
- [x] filter button on map overview incorrect hover behaviour
- [x] button link needs the darker pink
- [x] interactive event buttons wrong
- [x] budgeting vote button wrong
- [x] rating buttons wrong
- [x] poll buttons wrong

comments

- [x] filters vertical alignment off
- [x] readmore button wrong

labels

- [x] https://github.com/liqd/a4-meinberlin/issues/4488

**Comment by phillimorland** [comment]
@mcastro-lqd @CarolingerSeilchenspringer i'm gathering all the odd styling issues that came of deleting an old library here if you buttons or dropdowns or form fields looking weird please either add them to the list or link the issue here as it is all related. cheers!

**Comment by jostertag** [comment]
@phillimorland On the mobile version there are problems regarding the "Map" and "List" button. In some projects it is not possible to switch between the views, but it works on the desktop version. 
I don't know if this is what you meant under "filter button on map overview incorrect hover behaviour". Otherwise I can also open an issue if you like.

**Comment by phillimorland** [comment]
@jostertag please open an issue, hover behaviour refers to the styling that is displayed when the mouse hovers over the button, not to the button functionality
