### ISSUE TITLE
Buttons "Map" and "List" don't work properly on mobile version

### ISSUE THREAD

**Issue by jostertag** [liqd/a4-meinberlin#4523]
**URL:** https://meinberlin-dev.liqd.net/projekte/burgerhaushalt-3-phasen-testprojekt/
**user:** participant
**expected behaviour:** Changing the overview of the projects from map to list should work by clicking on the according button.
**behaviour:** On the mobile version there is a problem regarding the "Map" and "List" button. In most of the projects it is not possible to switch between the views, but it works on the desktop version.
**important screensize:** Samsung Galaxy S9+, Iphone 13
**device & browser:** Mobile phone Samsung Galaxy S9+, Google Chrome; Iphone 13, Safari
**Comment/Question:** Both buttons work also on the mobile version, however, on the project https://meinberlin-dev.liqd.net/projekte/carolin-findet-ihrberlin-2/ . For this project there are no filter options neither for the map nor for the list (except for the list sorting function). Maybe it has something to do with that.

**Comment by fuzzylogic2000** [comment]
Oh yes, when it works for no filters, it could have sth. to do with that. @khamui @Rineee You both had a look into the filters and the map/list switch recently. Any ideas?

**Comment by phillimorland** [comment]
@khamui as you are working on this anyway I assigned you, feel free to rm :p

**Comment by khamui** [comment]
This issue is not related to the budgeting (react list), so the mentioned PR #4573 won't fix this.

@jostertag the `Comment/Question` of this issue looks like another kind of unrelated issue. Do you mind to create another issue, separated from this one?

I checked this issue and indeed the switch button is there, but is not clickable in the mentioned screensizes. Because it is unrelated I will unassign and make this issue "pickable", as currently i am on another issue.
