### ISSUE TITLE
comment count missing on react list

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#4597]
**URL:** https://meinberlin-dev.liqd.net/projekte/burgerhaushalt-3-phasen-testprojekt/?initialSlide=1&mode=list
**user:** any
**expected behaviour:** comment count is visible
**behaviour:** comment count is missing 
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?
<img width="733" alt="Bildschirmfoto 2022-10-21 um 13 46 38" src="https://user-images.githubusercontent.com/35491681/197189054-3c50cf45-a4e8-4b06-8c7b-82df806a866a.png">

**Comment by fuzzylogic2000** [comment]
I think, the whole rating and comment count wasn't there when the vote button is shown? And we use different ways of determining what we show. :( So, this is likely an admin issue?

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 I have the view also as member of a group. But you are right, they are not in the design for voting phase. As the comments are always displayed in proposal detail it make sense to show them also in voting? Let's keep the issue open and discuss again later.

**Comment by Rineee** [comment]
@fuzzylogic2000 I could change it now to always show the comment count, as far as I understood Caro that would be her preferred solution.. any objections to doing that from your side?

**Comment by fuzzylogic2000** [comment]
> @fuzzylogic2000 I could change it now to always show the comment count, as far as I understood Caro that would be her preferred solution.. any objections to doing that from your side?

@Rineee But only if the voting phase isn't active and the button is shown, right?

Go for it, though!

**Comment by Rineee** [comment]
@fuzzylogic2000 Now Im confused.. no, I thought Caro meant to also show the comment count during voting phase, so actually always show it? At the moment we have 
`        permissions['view_comment_count'] = (
            self.module.has_feature('comment', Proposal)
            and not has_feature_active(self.module, Proposal, 'vote')
        )
`
so I would remove the has_feature_active_part?

**Comment by fuzzylogic2000** [comment]
@Rineee True, she says so in the issue. But I am still sure that we didn't want to change that. From the screenshot I thought that the button was there because she was admin and not because of the phase. But when she wrote the issue, it was also the voting phase for the given project. Soooooo, don't know.
I think, we should still do it the other way round and not show the rating when the voting phase is active. So add the last bit to the view_rating as well?! And if that was totally wrong, I will change it next time.

**Comment by Rineee** [comment]
@fuzzylogic2000 Now I am even more confused :exploding_head: 
I was going to remove the rating count entirely from 3 phase budgeting and only show support (during support phase and between support and voting). I talked to Caro the other day that we can ignore the 3 phase modules that still have rating phase instead of support phase (so they would be broken then, i.e. neither show support nor rating).
Comment count I thought would make sense to show always (as Caro wrote), but in your opinion we should not show it during voting still? Sorry, if I didnt get it :see_no_evil:

**Comment by Rineee** [comment]
Okay thanks, and also sorry for bugging you! 
I also think we did decide at some point that we didnt want to show the comment count during voting (why?), but also think now it makes more sense to actually show them.. so I'll change it and if that was wrong, we just change it back :grin:
