### ISSUE TITLE
#6669 [mB] redesign status (ampel) and feedback to the contribution

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#4852]
**URL:** https://meinberlin-dev.liqd.net/budgeting/2022-00958/
**user:** *all*
**important screensize:** *Both*
**device & browser:** *Safari Version 16.1 (18614.2.9.1.12)*
**Comment/Question:** *The Feedback title is still 24pt, can we make them 20pt so that the idea title is still bigger?* 

![Screenshot 2023-01-17 at 18 10 23](https://user-images.githubusercontent.com/59610786/212965727-b6ae9e81-3b93-49b5-ac58-c4f4b649e212.png)

**Comment by fuzzylogic2000** [comment]
Actually, we are overwriting the font size for the idea title (h1) to be the size of an h2. Can we also instead make the idea title bigger again instead of also overwriting the size of the h2?
But if that would look weird, we can also change it to smaller! We would also change the one for the moderation box then, though.

**Comment by khamui** [comment]
fixed here:
https://github.com/liqd/a4-meinberlin/pull/4929

**Comment by khamui** [comment]
> Actually, we are overwriting the font size for the idea title (h1) to be the size of an h2. Can we also instead make the idea title bigger again instead of also overwriting the size of the h2?
> But if that would look weird, we can also change it to smaller! We would also change the one for the moderation box then, though.

@fuzzylogic2000 we figured out that it appears very huge. So we had to go with modifying h2's font size.
