### ISSUE TITLE
Dashboard: "Moderation" needs short description

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-meinberlin#826]
"Moderator*innen" is still in English, and also a description of what moderators are able to do is still missing (and would be nice)

**Comment by xi** [comment]
This feature was added in #810 and did not get a translation yet. We will add a translation shortly (most imporantly: before deploying it to a production server). So this is not an issue.

**Comment by hmkay** [comment]
I guess this would be rather categorized as "concept" as it needs a definition of the role of moderators. What do you think @xi ?

**Comment by xi** [comment]
You are right. I see two questions here:

- What exactly *are* moderators?
- How do we want to present that information to users? The issue here is that we need to remember updating the information whenever the definition of moderator changes. We also need to decide whether we want to add this help text to the software itself or to the accompanying documentation.

**Comment by 2e2a** [comment]
Overall the moderator role is not fully defined yet. Currently moderators can:

1. Edit/Delete proposals
2. Set a moderator statement and proposal status for budgeting and kiezkasse

There is also an ongoing discussion to allow moderators to edit single projects.

**Comment by kleingeist** [comment]
with #923 moderators are also allowed to edit the project and view draft projects
