### ISSUE TITLE
No red exclamation mark next to date in external projects

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-meinberlin#924]
If you make a project (in this case: external) and you did not set the date yet, there is the red exclamation mark next to "settings" to indicate that there is still some information missing. Anyhow, there is no exclamation mark next to the star/end date (in case of a missing url, there is an exclamation mark right next to "url").

**Comment by xi** [comment]
The problem seems to be that we manually add the start_date and end_date fields to an otherwise automatically generated model form. This is necessary because the start_date/end_date are properties of the phase while everything else is properties of the project.

The `required_for_project_publish` only accepts model fields, not form fields. So we can not add start_date and end_date there.

**Comment by phillimorland** [comment]
if we cannot add start_date and end_date and therefore not fix it shall we close? I have added reminder label for future possible fix for now? @fuzzylogic2000

**Comment by fuzzylogic2000** [comment]
@phillimorland Yes, adding a reminder label is be a good idea, closing it not. It seems like it should behave the proposed way and if we close it, we will never find it again.

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland @fuzzylogic2000 are external projects supposed to be able to not set a date? With the new filter we have the problem that external projects without a date now run under the category "abgeschlossen". Can we make the date obligatory so that we have it more clear when an external project is running or over? I am not sure I got all of the above  discussion right, but if setting the date for external projects is not obligatory so far, then this is not an issue and I can make a story out of it.

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer Yes, that's true, external projects do not need to set dates. Only if they add one of the dates (either a start or an end-date) they are also required to set the other one. But I am pretty sure, that this was a requirement?!

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 probably it was a requirement but neither I nor our client sees the point in it. And since with the new filter we differentiate between running and finished projects we need this info. So I suggest we make a story out of it, if you say we can make it obligatory even though it hasn't been before?!

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer Yes, good idea!
